### PR TITLE
SuperpoweredOfflineAnalyzerExample

### PR DESCRIPTION
**Pull request by hsin919**
# SuperpoweredOfflineAnalyzerExample

A sample to show how to use SuperpoweredOfflineAnalyzer.

### CODE REVIEW

**Comment by Onizuka1117** [comment]
Good

**Comment by superpoweredSDK** [comment]
Thank you very much for your contribution. The next update will come with an example, with a slightly improved performance (no buffer pool).

**Comment by tabahkanlahhati** [comment]
On pull request

**Comment by tabahkanlahhati** [comment]
On gull request

**Pull request closed without merging**
